id: IsolateMachine-Generic-Test
version: -1
name: IsolateMachine-Generic-Test
description: A test for the generic machine isolation. Currently, the test is testing
  only Carbon Black Enterprise. After isolating the machine successfully, it also
  releases the machine from isolation.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: af50cbc5-7cc0-4946-8f16-c9cb501c15c2
    type: start
    task:
      id: af50cbc5-7cc0-4946-8f16-c9cb501c15c2
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": -110
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 07a13c11-af82-4f3b-8dae-a4de8d53aec5
    type: playbook
    task:
      id: 07a13c11-af82-4f3b-8dae-a4de8d53aec5
      version: -1
      name: Isolate Machine - Generic
      description: A generic playbook for isolating machines. This playbook uses the
        different integrations available to block connections to and from an endpoint
        in the network.
      playbookName: Isolate Machine - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      Hostname:
        complex:
          root: Endpoint
          accessor: Hostname
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 470,
          "y": 200
        }
      }
    note: false
  "2":
    id: "2"
    taskid: ba09cc47-327e-4494-8c1f-1c7206cfc2e7
    type: regular
    task:
      id: ba09cc47-327e-4494-8c1f-1c7206cfc2e7
      version: -1
      name: Release machine from isolation - Carbon Black Enterprise Response
      description: Releases a machine from isolation, using Carbon Black Enterprise
        Response.
      script: '|||cb-unquarantine-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      sensor:
        complex:
          root: CbResponse
          accessor: Sensors.CbSensorID
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 360
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 45d4c516-d936-435a-8586-523435ff22dc
    type: title
    task:
      id: 45d4c516-d936-435a-8586-523435ff22dc
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 520
        }
      }
    note: false
  "4":
    id: "4"
    taskid: f0d23815-7f28-479d-8e0b-b5bbdf305142
    type: regular
    task:
      id: f0d23815-7f28-479d-8e0b-b5bbdf305142
      version: -1
      name: Set hostname for isolation in context
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append: {}
      key:
        simple: Endpoint.Hostname
      value:
        simple: WIN-HQA3IUOV1NT
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 40
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 695,
        "width": 380,
        "x": 470,
        "y": -110
      }
    }
  }
inputs: []
outputs: []
