id: QRadar - Get offense correlations
version: -1
name: QRadar - Get offense correlations
fromversion: 4.0.0
description: |-
  Run on a QRadar offense to get more information

  * Get all correlations relevant to the offense
  * Get all logs relevant to the correlations (not done by default, set "GetCorrelationLogs" to "True")

  Inputs:
  * GetCorrelationLogs (default: False)
  * MaxLogsCount (default: 20)
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 608f0ec1-4001-4e68-8ead-e160f7802b35
    type: start
    task:
      id: 608f0ec1-4001-4e68-8ead-e160f7802b35
      version: -1
      name: ""
      description: Start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: bde9aea2-4775-45e5-870c-72fb78d05dfc
    type: condition
    task:
      id: bde9aea2-4775-45e5-870c-72fb78d05dfc
      version: -1
      name: Is this a QRadar offense?
      description: Check whether this a QRadar offense
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: QRadar
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: edc69a27-88bc-4edb-8fca-8a111d2b6785
    type: title
    task:
      id: edc69a27-88bc-4edb-8fca-8a111d2b6785
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1390
        }
      }
    note: false
  "5":
    id: "5"
    taskid: d05103bc-af8a-4d0b-80e2-a1637c45aa9c
    type: title
    task:
      id: d05103bc-af8a-4d0b-80e2-a1637c45aa9c
      version: -1
      name: Get offense information
      description: Get the offense information
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
  "6":
    id: "6"
    taskid: e31967fa-93c4-4cc0-816a-e2af47dbba93
    type: condition
    task:
      id: e31967fa-93c4-4cc0-816a-e2af47dbba93
      version: -1
      name: Should query for the correlations' logs?
      description: Checks whether to query for the correlation logs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "YES":
      - "15"
    separatecontext: false
    conditions:
    - label: "YES"
      condition:
      - - operator: isNotEqualString
          left:
            value:
              simple: inputs.GetCorrelationLogs
            iscontext: true
          right:
            value:
              simple: "False"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 865
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 363172d6-cea9-4192-81b1-e278acb51298
    type: regular
    task:
      id: 363172d6-cea9-4192-81b1-e278acb51298
      version: -1
      name: Transform StartTime to unix
      description: If the given startTime is in date string, transforms it for the qradar-searches command
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      append: {}
      key:
        simple: Inputs.Modified.StartTime
      value:
        complex:
          root: inputs.StartTime
          transformers:
          - operator: toUnix
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 515
        }
      }
    note: false
  "12":
    id: "12"
    taskid: a2ab59d6-2601-488b-80ab-e67cf8d17196
    type: regular
    task:
      id: a2ab59d6-2601-488b-80ab-e67cf8d17196
      version: -1
      name: Clean up context
      description: Cleans up the context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Inputs.Modified.StartTime
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1215
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 81e5564a-60f2-447c-887e-521100e9bba8
    type: playbook
    task:
      id: 81e5564a-60f2-447c-887e-521100e9bba8
      version: -1
      name: QRadarFullSearch
      description: This playbook runs a QRadar query and return its results to the
        context.
      playbookName: QRadarFullSearch
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      headers: {}
      interval:
        complex:
          root: inputs.Interval
      output_path:
        simple: QRadar.Correlation
      query_expression:
        simple: SELECT identityip as "Identityip", destinationport as "Destinationport",
          magnitude as "Magnitude", protocolid as "Protocolid", eventcount as "Eventcount",
          logsourceid as "Logsourceid", sourceport as "Sourceport", starttime as "StartTime",qid
          as "QID",destinationip as "DestinationIP",category as "CategoryID",username
          as "Username",sourceip as "SourceIP","CRE Name" as "CREName","CRE Description"
          as "CREDescription",CATEGORYNAME(highlevelcategory) as "Category" FROM events
          WHERE "CRE NAME" <> NULL AND INOFFENSE(${inputs.ID}) START '${Inputs.Modified.StartTime}'
      range:
        simple: 0-${inputs.MaxLogsCount}
      timeout:
        complex:
          root: inputs.Timeout
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 690
        }
      }
    note: false
  "15":
    id: "15"
    taskid: c9da347e-2137-4182-8a7b-ca73232d24f9
    type: playbook
    task:
      id: c9da347e-2137-4182-8a7b-ca73232d24f9
      version: -1
      name: QRadarFullSearch
      description: This playbook runs a QRadar query and return its results to the
        context.
      playbookName: QRadarFullSearch
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      headers: {}
      interval:
        complex:
          root: inputs.Interval
      output_path:
        simple: QRadar.Log
      query_expression:
        simple: select RULENAME(${QRadar.Correlation.[0].QID}) as "Rulename_${QRadar.Correlation.[0].QID}",
                  sourceip as "SourceIP", destinationip as "DestinationIP", eventcount as
                  "EventCount", sourceport as "SourcePort", username as "Username", starttime
                  as "StartTime", destinationport as "DestinationPort", magnitude as "Magnitude",
                  identityip as "IdentityIP", CATEGORYNAME(category) as "Category", PROTOCOLNAME(protocolid)
                  as "ProtocolName", LOGSOURCENAME(logsourceid) as "Logsourcename_Logsourceid"
                  from events where "CRE Name" IS NULL AND INOFFENSE(${inputs.ID}) START '${Inputs.Modified.StartTime}'
      range:
        simple: 0-${inputs.MaxLogsCount}
      timeout:
        complex:
          root: inputs.Timeout
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: GetCorrelationLogs
  value:
    simple: "False"
  required: false
  description: If "True" will get all of the offense's correlations logs
- key: MaxLogsCount
  value:
    simple: "20"
  required: false
  description: 'Maximum number of log entires to query from QRadar (default: 20)'
- key: ID
  value:
    complex:
      root: incident
      accessor: labels.id
  required: true
  description: 'The QRadar offense ID '
- key: StartTime
  value:
    complex:
      root: incident
      accessor: labels.start_time
  required: true
  description: The QRadar offense start time
- key: Timeout
  value:
    simple: "10"
  required: false
  description: Time (in minutes) before playbook queries timeout.
- key: Interval
  value:
    simple: "1"
  required: false
  description: Time (in minutes) between each query check.
outputs:
- contextPath: QRadar.Correlation.StartTime
  description: The correlation start time
- contextPath: QRadar.Correlation.CategoryID
  description: 'The correlation category id '
- contextPath: QRadar.Correlation.QID
  description: The correlation QID identifier
- contextPath: QRadar.Correlation.CREName
  description: The correlation name
- contextPath: QRadar.Correlation.CREDescription
  description: The correlation description
- contextPath: QRadar.Correlation
  description: The QRadar offense correlations
- contextPath: QRadar.Correlation.SourceIP
  description: The correlation source IP
- contextPath: QRadar
  description: QRadar context output
- contextPath: QRadar.Correlation.DestinationIP
  description: The correlation destination IP
- contextPath: QRadar.Correlation.Category
  description: The correlation high level category
- contextPath: QRadar.Correlation.Username
  description: The correlation username
- contextPath: QRadar.Log
  description: The QRadar offense correlation logs
- contextPath: QRadar.Log.QID
  description: The log's correlation ID
- contextPath: QRadar.Log.SourceIP
  description: The log's source IP
- contextPath: QRadar.Log.DestinationPort
  description: The log's destination port
- contextPath: QRadar.Log.SourcePort
  description: The log's source port
- contextPath: QRadar.Log.DestinationIP
  description: The log's destination IP
- contextPath: QRadar.Log.Category
  description: The log's category
- contextPath: QRadar.Log.IdentityIP
  description: The log's identity IP
- contextPath: QRadar.Log.Username
  description: The log's username
- contextPath: QRadar.Log.StartTime
  description: The log's start time
- contextPath: QRadar.Log.Magnitude
  description: The log's magnitude
- contextPath: QRadar.Log.ProtocolName
  description: The log's protocol name
releaseNotes: "Created QRadarGetCorrelationLogs playbook - an alternative to QRadarGetCorrelationLogs automation."
tests:
- test_QRadar-Get_offense_correlations
