id: Isolate Machine - Carbon Black Enterprise Response
version: -1
name: Isolate Machine - Carbon Black Enterprise Response
fromversion: 4.0.0
description: Carbon Black Response - isolate an endpoint, given a hostname.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 284e87a4-5924-499c-8ec5-dcdd60ff3a7f
    type: start
    task:
      id: 284e87a4-5924-499c-8ec5-dcdd60ff3a7f
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
  "2":
    id: "2"
    taskid: fce0d008-62e1-4abe-86e6-bda7a3f03354
    type: regular
    task:
      id: fce0d008-62e1-4abe-86e6-bda7a3f03354
      version: -1
      name: Get host information from Carbon Black Enterprise Response
      description: Gets the sensor ID of the hostname that is about to be isolated.
        The sensor ID is being used by Carbon Black Enterprise Response to isolate
        the machine.
      script: '|||cb-sensor-info'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      groupid: {}
      hostname:
        complex:
          root: inputs.Hostname
      ip: {}
      sensor: {}
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
  "3":
    id: "3"
    taskid: f9c9ab5d-ec58-4926-8819-49acce756b77
    type: regular
    task:
      id: f9c9ab5d-ec58-4926-8819-49acce756b77
      version: -1
      name: Isolate hostname
      description: Isolates the machine from the network, using Carbon Black Enterprise
        Response.
      script: '|||cb-quarantine-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      sensor:
        complex:
          root: CbResponse
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: CbResponse.Sensors.Hostname
                iscontext: true
              right:
                value:
                  simple: inputs.Hostname
                iscontext: true
          accessor: Sensors.CbSensorID
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 920
        }
      }
    note: false
  "4":
    id: "4"
    taskid: b22f0eaf-c0bc-4299-83c8-381f76cd99e8
    type: title
    task:
      id: b22f0eaf-c0bc-4299-83c8-381f76cd99e8
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1300
        }
      }
    note: false
  "5":
    id: "5"
    taskid: ca2d6758-fb8f-4377-8d7a-857d38a1206b
    type: condition
    task:
      id: ca2d6758-fb8f-4377-8d7a-857d38a1206b
      version: -1
      name: Is Carbon Black Enterprise Response enabled?
      description: Checks whether Carbon black Enterprise Response is active.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblack-v2
                - - operator: isEqualString
                    left:
                      value:
                        simple: state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 170
        }
      }
    note: false
  "6":
    id: "6"
    taskid: c3d9143e-0bb5-476a-8743-3226cdd1a8be
    type: condition
    task:
      id: c3d9143e-0bb5-476a-8743-3226cdd1a8be
      version: -1
      name: Is there an endpoint to isolate?
      description: Checks whether a hostname of a machine to isolate was given to
        the playbook.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Hostname
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 360
        }
      }
    note: false
  "7":
    id: "7"
    taskid: e95eae9b-29c1-4101-89d3-31f91c2ebab9
    type: title
    task:
      id: e95eae9b-29c1-4101-89d3-31f91c2ebab9
      version: -1
      name: Integration disabled / No endpoint given
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 790,
          "y": 455
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 7365eb28-9ff9-4aad-8306-5fea8c178fc6
    type: condition
    task:
      id: 7365eb28-9ff9-4aad-8306-5fea8c178fc6
      version: -1
      name: Is endpoint available for isolation?
      description: Checks if the endpoint can be isolated, by checking whether a corresponding
        sensor for the endpoint was retrieved,  and whether the endpoint is not already
        isolated.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CbResponse
                accessor: Sensors.CbSensorID
            iscontext: true
      - - operator: isFalse
          left:
            value:
              complex:
                root: CbResponse
                accessor: Sensors.Isolated
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 710
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 2eed236d-2870-4d03-8680-01f6769ac05d
    type: title
    task:
      id: 2eed236d-2870-4d03-8680-01f6769ac05d
      version: -1
      name: No sensor found / Already Isolated
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 790,
          "y": 920
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1315,
        "width": 1007.5,
        "x": 162.5,
        "y": 50
      }
    }
  }
inputs:
- key: Hostname
  value:
    complex:
      root: inputs.Hostname
  required: false
  description: The hostname of the machine that will be isolated.
outputs:
- contextPath: CbResponse.Sensors.CbSensorID
  description: Carbon Black Response Sensors ids that has been isolated
- contextPath: Endpoint
  description: The isolated enpoint
- contextPath: InIsolationSince
  description: The date when the isolation of the machine started
  type: date
releaseNotes: "-"
tests:
  - IsolateMachine-Generic-Test
